from pipeline.models.feature_select_linear import (
    GroupCurveBlendPredictor,
    GroupCurveRangeCalibratedPredictor,
    GroupCurveResidualPredictor,
    GroupCurveTemplateQuantilePredictor,
    GroupCurveTemplateRidgePredictor,
    GroupCurveTemplateWidePredictor,
    GroupCurveUpperAnchorPredictor,
    MetaMonotonicQuantileBlendPredictor,
    MetaMonotonicTopK5RidgePredictor,
    MetaMonotonicTopK6RidgePredictor,
    PlsHistGradientBoosting4Predictor,
    PlsHistGradientBoosting6Predictor,
    TopKFeatureElasticNetPredictor,
    TopKFeatureHuberPredictor,
    TopKFeatureRidge3Predictor,
    TopKFeatureRidge4Predictor,
    TopKFeatureRidge5Predictor,
    TopKFeatureRidge5Alpha30Predictor,
    TopKFeatureRidge5Alpha300Predictor,
    TopKFeatureRidge6Predictor,
    TopKFeatureRidge8Predictor,
    TopKFeatureRidge12Predictor,
    TopKFeatureRidgeCVPredictor,
    TopKFeatureStableRidge5Predictor,
    TopKHistGradientBoosting12Predictor,
    TopKHistGradientBoosting24Predictor,
    TopKQuantileBlendPredictor,
    TopKRidgeMeanShiftPredictor,
    TopKRidgeEnsemblePredictor,
    TopKRidgeUpperCalQ70Predictor,
    TopKRidgeUpperCalQ80Predictor,
    TopKWeightedRidge6Q70Predictor,
    TopKWeightedRidge6Q80Predictor,
    TopKWeightedRidge8Q70Predictor,
)
from pipeline.models.mean import MeanPredictor
from pipeline.models.nearest_train_species import (
    NearestTrainSpeciesBiasCorrectedPredictor,
    NearestTrainSpeciesLinearPredictor,
)
from pipeline.models.single_feature_linear import (
    SingleFeatureLinearClippedPredictor,
    SingleFeatureLinearLowTailMildPredictor,
    SingleFeatureLinearLowTailStrongPredictor,
    SingleFeatureFixedIndexPredictor,
    SingleFeatureLinearPredictor,
    DualStableWavelengthRidgePredictor,
    SingleFeatureLooConsensusWavelengthPredictor,
    DualPrepAnchorRawBlendPredictor,
    SingleFeatureTop3MedianPredictor,
    SingleFeatureLinearOofInterceptPredictor,
    SingleFeatureLooRmseWavelengthPredictor,
    SingleFeatureSecondWavelengthPredictor,
    SingleFeatureStableWavelengthPredictor,
    SingleFeatureLinearRangeCalibratedPredictor,
    MoistureBinWavelengthLinearPredictor,
    MoistureBinFixedWavelengthPredictor,
    MscSelectRawLinearPredictor,
)
from pipeline.models.sklearn_models import (
    BayesianRidgePredictor,
    ElasticNetPredictor,
    HuberPredictor,
    LogRidgeAlpha100Predictor,
    PcaRidgeC50Predictor,
    PlsC2Predictor,
    PlsC4Predictor,
    PlsC6Predictor,
    PlsC8Predictor,
    PlsC12Predictor,
    PlsC16Predictor,
    RidgeAlpha1Predictor,
    RidgeAlpha10Predictor,
    RidgeAlpha100Predictor,
    RidgeAlpha1000Predictor,
    SvrLinearC1Predictor,
    SvrRbfC10Predictor,
)
from pipeline.models.topk_sgd_linear import TopKSgdLinearPredictor
from pipeline.models.topk_sgd_linear_clipped import TopKSgdLinearClippedPredictor

PREDICTOR_REGISTRY: dict[str, type] = {
    "mean": MeanPredictor,
    "single_feature_linear": SingleFeatureLinearPredictor,
    "single_feature_fixed_index": SingleFeatureFixedIndexPredictor,
    "single_feature_stable_wavelength": SingleFeatureStableWavelengthPredictor,
    "single_feature_loo_consensus_wavelength": SingleFeatureLooConsensusWavelengthPredictor,
    "dual_prep_anchor_raw_blend": DualPrepAnchorRawBlendPredictor,
    "nearest_train_species_linear": NearestTrainSpeciesLinearPredictor,
    "nearest_train_species_bias_corrected": NearestTrainSpeciesBiasCorrectedPredictor,
    "single_feature_top3_median": SingleFeatureTop3MedianPredictor,
    "single_feature_linear_oof_intercept": SingleFeatureLinearOofInterceptPredictor,
    "single_feature_loo_rmse_wavelength": SingleFeatureLooRmseWavelengthPredictor,
    "single_feature_second_wavelength": SingleFeatureSecondWavelengthPredictor,
    "dual_stable_wavelength_ridge": DualStableWavelengthRidgePredictor,
    "single_feature_linear_clipped": SingleFeatureLinearClippedPredictor,
    "single_feature_linear_low_tail_mild": SingleFeatureLinearLowTailMildPredictor,
    "single_feature_linear_low_tail_strong": SingleFeatureLinearLowTailStrongPredictor,
    "single_feature_linear_range_calibrated": SingleFeatureLinearRangeCalibratedPredictor,
    "moisture_bin_wavelength_linear": MoistureBinWavelengthLinearPredictor,
    "moisture_bin_fixed_wavelength": MoistureBinFixedWavelengthPredictor,
    "msc_select_raw_linear": MscSelectRawLinearPredictor,
    "topk3_ridge": TopKFeatureRidge3Predictor,
    "topk4_ridge": TopKFeatureRidge4Predictor,
    "topk5_ridge": TopKFeatureRidge5Predictor,
    "topk6_ridge": TopKFeatureRidge6Predictor,
    "topk8_ridge": TopKFeatureRidge8Predictor,
    "topk12_ridge": TopKFeatureRidge12Predictor,
    "topk5_ridge_a30": TopKFeatureRidge5Alpha30Predictor,
    "topk5_ridge_a300": TopKFeatureRidge5Alpha300Predictor,
    "topk5_stable_ridge": TopKFeatureStableRidge5Predictor,
    "topk_ridge_cv": TopKFeatureRidgeCVPredictor,
    "topk_elastic": TopKFeatureElasticNetPredictor,
    "topk_huber": TopKFeatureHuberPredictor,
    "topk_ridge_ensemble": TopKRidgeEnsemblePredictor,
    "topk6_weighted_q70": TopKWeightedRidge6Q70Predictor,
    "topk6_weighted_q80": TopKWeightedRidge6Q80Predictor,
    "topk8_weighted_q70": TopKWeightedRidge8Q70Predictor,
    "topk_quantile_blend": TopKQuantileBlendPredictor,
    "meta_monotonic_topk5_ridge": MetaMonotonicTopK5RidgePredictor,
    "meta_monotonic_topk6_ridge": MetaMonotonicTopK6RidgePredictor,
    "meta_monotonic_quantile_blend": MetaMonotonicQuantileBlendPredictor,
    "group_curve_template_quantile": GroupCurveTemplateQuantilePredictor,
    "group_curve_template_ridge": GroupCurveTemplateRidgePredictor,
    "group_curve_template_wide": GroupCurveTemplateWidePredictor,
    "group_curve_upper_anchor": GroupCurveUpperAnchorPredictor,
    "group_curve_range_calibrated": GroupCurveRangeCalibratedPredictor,
    "group_curve_blend": GroupCurveBlendPredictor,
    "group_curve_residual": GroupCurveResidualPredictor,
    "topk12_hgbdt": TopKHistGradientBoosting12Predictor,
    "topk24_hgbdt": TopKHistGradientBoosting24Predictor,
    "pls4_hgbdt": PlsHistGradientBoosting4Predictor,
    "pls6_hgbdt": PlsHistGradientBoosting6Predictor,
    "topk6_upper_cal_q70": TopKRidgeUpperCalQ70Predictor,
    "topk6_upper_cal_q80": TopKRidgeUpperCalQ80Predictor,
    "topk6_mean_shift": TopKRidgeMeanShiftPredictor,
    "ridge_alpha1": RidgeAlpha1Predictor,
    "ridge_alpha10": RidgeAlpha10Predictor,
    "ridge_alpha100": RidgeAlpha100Predictor,
    "ridge_alpha1000": RidgeAlpha1000Predictor,
    "log_ridge_alpha100": LogRidgeAlpha100Predictor,
    "elastic_net": ElasticNetPredictor,
    "bayesian_ridge": BayesianRidgePredictor,
    "huber": HuberPredictor,
    "pca50_ridge_alpha100": PcaRidgeC50Predictor,
    "svr_rbf_c10": SvrRbfC10Predictor,
    "svr_linear_c1": SvrLinearC1Predictor,
    "pls_c2": PlsC2Predictor,
    "pls_c4": PlsC4Predictor,
    "pls_c6": PlsC6Predictor,
    "pls_c8": PlsC8Predictor,
    "pls_c12": PlsC12Predictor,
    "pls_c16": PlsC16Predictor,
    "topk_sgd_linear": TopKSgdLinearPredictor,
    "topk_sgd_linear_clipped": TopKSgdLinearClippedPredictor,
}


def get_predictor(name: str):
    if name not in PREDICTOR_REGISTRY:
        raise KeyError(f"未知の predictor: {name}. 利用可能: {list(PREDICTOR_REGISTRY)}")
    return PREDICTOR_REGISTRY[name]()
